### PR TITLE
Instead of RNDTRE04 assign RNDTRE08 as creature loot in BGT and EET

### PR DESCRIPTION
**Pull request by Ychap**

### CODE REVIEW

**Comment by Gitjas** [comment]
We took the assignment of RNDTRE08 out because it lead to too powerful loot in the BG1 part. 
I will not reinsert it.

**Comment by Ychap** [comment]
I'm not sure if we are on the same page. But the current behavior leads to too powerful loot in BGT and EET.
I just experienced this behavior in-game: On my EET run ACGNOLL1.CRE with 3 RNDTRE04 dropped scrolls for Mass Invisibility and Protection From Energy!

The reason behind is, that BGT and EET are changing RNDTREAS.2DA:
RNDTRE01 up to RNDTRE05 is for BG2 loot, RNDMAG06 and RNDTRE06 up to RNDTRE09 is for BG1 loot.

\
You already implemented this distinction in some places for BGT:
https://github.com/Gitjas/Ascalons_Questpack/blob/b49e1db303dc9bc63557f7cec3ba67fb1679e425/AC_QUEST/tpa/hopsi.tpa#L15-L20 https://github.com/Gitjas/Ascalons_Questpack/blob/b49e1db303dc9bc63557f7cec3ba67fb1679e425/AC_QUEST/tpa/wolves_and_men.tpa#L30-L37

**Comment by Gitjas** [comment]
Weird. We'll look into it, thanks!

**Comment by Ychap** [comment]
Thanks for your investigation!

Here are the contents of RNDTREAS.2DA, RNDMAGIC.2DA and RNDSCROL.2DA from my EET install, where this behavior happened. Maybe it helps. 🙂

\
RNDTREAS.2DA:
```
2DA      V1.0
*
         2        3        4        5        6        7        8        9        10       11       12       13       14       15       16       17       18       19       20
POOR     MISC19   004      SCRL75   001      001      001      001      001      001      001      001      001      001      001      002      002      003      003      MISC16
AVERAGE  RNDMAG01 MISC23   AMUL05   MISC17   015      012      SCRL75   008      006      003      001      001      007      009      RNDSCR01 MISC18   MISC22   AMUL06   RNDMAG01
WELL_OFF RNDMAG01 RNDMAG01 AMUL08   MISC20   034      AMUL09   RNDSCR01 008      009      RING11   023      RNDSCR01 RING14   MISC26   MISC25   057      MISC27   MISC28   RNDMAG01
WEALTHY  RNDMAG02 RNDMAG01 MISC37   MISC35   RING16   AMUL07   RNDSCR02 047      038      029      AMUL09   RING10   RING15   RNDSCR02 RING13   RING17   MISC34   RNDMAG01 RNDMAG02
RICH     RNDMAG02 RNDMAG02 RNDMAG01 RNDMAG01 AMUL12   AMUL13   AMUL10   MISC29   MISC21   073      MISC24   RNDSCR03 MISC34   MISC38   RNDSCR03 RNDMAG01 RNDMAG01 RNDMAG02 RNDMAG02
AVRG_BG1 RNDMAG03 MISC23   AMUL05   MISC17   015      012      010      008      006      003      001      001      007      009      RNDSCR04 MISC18   MISC22   AMUL06   RING12
WELL_BG1 RNDMAG03 MISC31   AMUL08   MISC20   034      AMUL09   RNDSCR04 008      009      RING11   023      RNDSCR04 RING14   MISC26   MISC25   057      MISC27   MISC28   AMUL04
WEAL_BG1 RNDMAG03 RING18   MISC37   MISC35   RING16   AMUL07   RNDSCR05 047      038      029      AMUL09   RING10   RING15   RNDSCR05 RING13   RING17   MISC34   MISC36   RNDMAG04
RICH_BG1 RNDMAG04 RNDMAG03 MISC43   AMUL11   AMUL12   AMUL13   AMUL10   MISC29   MISC21   073      MISC24   RNDSCR06 MISC34   MISC38   RNDSCR06 MISC40   MISC42   RNDMAG03 RNDMAG04
```

RNDMAGIC.2DA:
```
2DA       V1.0
*
          2         3         4         5         6         7         8         9         10        11        12        13        14        15        16        17        18        19        20
LOW       RNDWEP02  RNDWEP01  BULL03*3  POTN31    RNDSCR02  RNDSCR01  SCRL06    SCRL04    POTN08    POTN43    POTN44    POTN37    POTN19    POTN28    BULL02*5  AROW02*5  BOLT02*5  RNDWEP01  RNDWEP02
HIGH      RNDWEP03  RNDWEP02  RNDWEP01  SCRL08    SCRL09    RNDSCR03  SCRL16    POTN17    POTN08    POTN10    AROW04    AROW09    BOLT04    BOLT03    AROW06    RNDWEP01  RNDWEP02  RNDWEP02  RNDWEP03
LOW_BG1   AROW07    BOLT05    BULL03*3  POTN31    RNDSCR05  RNDSCR04  SCRL06    SCRL04    POTN08    POTN43    POTN44    POTN37    POTN19    POTN28    BULL02*5  AROW02*5  BOLT02*5  AROW11*3  BOLT06*3
HIGH_BG1  POTN09    POTN05    POTN03    SCRL08    SCRL09    RNDSCR06  SCRL16    POTN17    POTN08    POTN10    AROW04    AROW09    BOLT04    BOLT03    AROW06    AROW08    WAND03*10 WAND05*10 WAND06*10
POOP_BG1  POTN08    POTN13    POTN08    POTN36    POTN08    RNDSCR06  POTN08    SCRL91    POTN08    POTN18    POTN08    BOLT04*4  POTN08    AROW09*2  POTN08    WAND07*4  RNDSCR07  POTN08    SW1H22
POOR_BG1  MISC19    004       002       001       RNDSCR04  001       001       AMUL02    RING01    001       001       001       001       001       002       002       003       003       MISC16
```

RNDSCROL.2DA:
```
2DA     V1.0
*
        1       2       3       4       5       6       7       8       9       10      11      12      13      14      15      16      17      18      19      20
1st     SCRL6N  SCRL6T  SCRL70  SCRL66  SCRL66  SCRL67  SCRL68  SCRL69  SCRL71  SCRL72  SCRL73  SCRL75  SCRL76  SCRL77  SCRL78  SCRL79  SCRL80  SCRL7M  SCRL7L  SCRL7K
2nd     SCRL8M  SCRL8Q  SCRL8R  SCRL8S  SCRL8T  SCRL8U  SCRL8V  SCRL8W  SCRL8X  SCRL8Y  SCRL8Z  SCRL7B  SCRL7C  SCRL7D  SCRL7E  SCRL7F  SCRL7G  SCRL7H  SCRL7I  SCRL7J
3rd     SCRL9L  SCRL9G  SCRL9F  SCRL9E  SCRL9D  SCRL9C  SCRL9B  SCRL9A  SCRL8A  SCRL8B  SCRL8C  SCRL8D  SCRL8E  SCRL8F  SCRL8G  SCRL8H  SCRL8I  SCRL8J  SCRL8L  SCRL8M
1st_BG1 SCRL84  SCRL70  SCRL70  SCRL66  SCRL66  SCRL67  SCRL68  SCRL69  SCRL71  SCRL72  SCRL73  SCRL75  SCRL76  SCRL77  SCRL78  SCRL79  SCRL80  SCRL81  SCRL82  SCRL83
2nd_BG1 SCRL85  SCRL85  SCRL86  SCRL86  SCRL87  SCRL87  SCRL89  SCRL90  SCRL91  SCRL92  SCRL93  SCRL94  SCRL95  SCRL96  SCRL97  SCRL98  SCRL99  SCRL1B  SCRL1C  SCRL1C
3rd_BG1 SCRL1D  SCRL1E  SCRL1F  SCRL1G  SCRL1H  SCRL1I  SCRL1J  SCRL1K  SCRL1L  SCRL1M  SCRL1N  SCRL1O  SCRL1P  SCRL1Q  SCRL1S  SCRL1S  SCRL1T  SCRL1E  SCRL1M  SCRL1I
4th_BG1 SCRL5A  SCRL5B  SCRL5C  SCRL5D  SCRL5G  SCRL5H  SCRL5I  SCRL5J  SCRL5K  SCRL2F  SCRL5M  SCRL1Z  SCRL2A  SCRL1U  SCRL1T  SCRL5M  SCRL56  SCRL58  SCRL59  SCRL5J
```

**Pull request merged**
